python:
  executable:
    path: C:/Users/User/AppData/Local/Programs/Python/Python310/python.exe
  root:
    path: C:/LocBootProject/workspace/MyBaseLinkV2
  working:
    dir: "${python.root.path}/python"
  update_stock_listing:
    path: "${python.root.path}/python/stock/py/update_stock_listing.py"
  stock:
    stock_listing:
      path: "${python.root.path}/python/stock/stock_list/stock_listing.json"

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: MYBASEUSER
    password: mybaseuser1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        default_schema: MYBASEUSER

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
